### PR TITLE
Hiral assignment 19

### PR DESCRIPTION
**Pull request by purohit31**
### Assignment Description :notebook:

print first 5 even no using while & dowhile loop

### Evidence :file_folder:

image

### Checklist before requesting a review :ballot_box_with_check:

- [x] I have performed a self-review of my code
- [x] My changes generate no compile time errors

### CODE REVIEW

**Comment by purohit31** [comment]
i was not able to checkout to master file it was showing merge issue with this branch so i have created another pr. so plz merge it

**Comment by MargiVegada** [comment]
What you do with the classpath?

**Review by MargiVegada — CHANGES_REQUESTED** [review]
Delete that classpath from this pr only

**Comment by purohit31** [comment]
actually when git stash session, i did changes in this assignment (branch)and saved it and i stashed another branch also .may be after that session it was coming as unmerged file. so i have committed it again.

**Comment by purohit31** [comment]
how i can delete classpath?

**Comment by purohit31** [comment]
> i have deleted classpath. can you check and now u can merge it

**Comment by purohit31** [comment]
i have deleted classpath

**Pull request closed without merging**
