### PR TITLE
Hiral_Assignment_19

### PR DESCRIPTION
**Pull request by purohit31**
### Assignment Description :notebook:

Print the frequency of the given character from the given String without case sensitivity

### Evidence :file_folder:

image

### Checklist before requesting a review :ballot_box_with_check:

- [x] I have performed a self-review of my code
- [x] My changes generate no compile time errors

### CODE REVIEW

**Review by MargiVegada — CHANGES_REQUESTED** [review]
Add pr description and evidence

**Comment by purohit31** [comment]
i did changes in evidence and description plz check and approve it

**Comment by purohit31** [comment]
> Add pr description and evidence

i did changes. plz approve it.

**Review by MargiVegada — APPROVED** [review]
Indentation required, logic looks good to me

**Pull request merged**
